!identifiers hierarchical
hosting.cli -> hosting.master.api "Executes commands via REST/HTTP" "REST/HTTP"
hosting.master -> hosting.database "Reads and writes state" "SQLAlchemy / PostgreSQL"
hosting.master -> hosting.webAgent "Controls via REST/HTTP" "REST/HTTP"
hosting.webAgent -> hosting.master "Reports state and heartbeat via REST/HTTP" "REST/HTTP"
hosting.master -> hosting.dnsAgent "Controls via REST/HTTP" "REST/HTTP"
hosting.dnsAgent -> hosting.master "Reports state and heartbeat via REST/HTTP" "REST/HTTP"
hosting.master -> hosting.mailAgent "Controls via REST/HTTP" "REST/HTTP"
hosting.mailAgent -> hosting.master "Reports state and heartbeat via REST/HTTP" "REST/HTTP"
hosting.master -> hosting.dbAgent "Controls via REST/HTTP" "REST/HTTP"
hosting.dbAgent -> hosting.master "Reports state and heartbeat via REST/HTTP" "REST/HTTP"
